### ISSUE TITLE
Document how to configure Linux non-root device access

### ISSUE THREAD

**Issue by TotallyInformation** [natcl/node-red-project-template#1]
- Serialport?
- Bluetooth

**Comment by natcl** [comment]
Do you mean just `sudo npm start` ?

**Comment by TotallyInformation** [comment]
Sorry, added to the wrong repo!! I had yours and mine open side by side! Sorry. I'm trying to document how to use NR without any root/admin level access.

**Comment by natcl** [comment]
No worries :)
